spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    generate-ddl: true


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    contexts: production
#   breaks the application startup for some reason.
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
