spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS chat_service
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #  jackson:
  #    serialization:
  #      write-dates-as-timestamps: false

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_schema: chat_service

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS chat_service
    user: sa
    password:
    default-schema: chat_service
    contexts: development