create table acl_sid(
                        id bigint generated by default as identity(start with 100) not null primary key,
                        principal boolean not null,
                        sid varchar_ignorecase(100) not null,
                        constraint unique_uk_1 unique(sid,principal)
);

